#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    
    if [ "$1" == "start" ]; then
        docker-compose up -d
	    docker-sync start
    elif [ "$1" == "stop" ]; then
        docker-compose down
	    docker-sync stop
    elif [ "$1" == "artisan" ] || [ "$1" == "art" ]; then
        shift 1; #shift the commands 1 up. So `artisan` will get shifted off
        docker-compose exec \
            app \
            php artisan "$@"
    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1; #shift the commands 1 up. So `artisan` will get shifted off
        docker-compose exec \
            app \
            composer "$@"
    elif [ "$1" == "test" ]; then
        shift 1; #shift the commands 1 up. So `artisan` will get shifted off
        docker-compose exec \
            app \
            ./vendor/bin/phpunit "$@"
    elif [ "$1" == "npm" ]; then
        shift 1; #shift the commands 1 up. So `artisan` will get shifted off
        docker-compose run \
            node \
            npm "$@"
    else
        docker-compose "$@"
    fi

else
    docker-compose ps
fi
